# General discussion

In the preceding chapters, I have described a dual evolutionary framework of political ideology and presented the results of several empirical studies testing this framework. In particular, the empirical work has focused on testing one key prediction of the dual evolutionary theory: that variation in cooperative and conformist behavioural preferences should be related to the two dimensions of political ideology in modern humans. As I will discuss in detail below, the evidence thus far has largely supported this prediction, albeit with some important caveats. What is striking about this evidence, in my view, is that the incentivised behavioural tasks measuring cooperative and conformist preferences are highly abstract, contain no political framing or priming, and are often completed separately to the self-report surveys measuring political ideology. Despite this, we still observe robust relationships between behavioural preferences and political attitudes emerging from the data.

Below, I bring together the results of the four empirical chapters in this thesis, summarising what we have learned about the two dimensions of political ideology and feeding back to the theoretical framework. Finally, I conclude with several promising avenues for research aiming to test further predictions of the dual evolutionary foundations of political ideology.

## A tale of two dimensions: What have we learned about political ideology?

### The "economic" dimension of political ideology

In the transition from small great ape bands to more complex hunter-gatherer communities, humans became obligate cooperators, collaborating extensively in foraging, hunting, and infant care [@Tomasello2012; @Tomasello2016; @Sterelny2016; @Kramer2019]. Replacing the great ape system of dominance hierarchies, humans began to distribute food and resources relatively evenly among group members [@Boehm1993]. Chapter 2 argues that this shift from competitive hierarchy to cooperative egalitarianism explains the domain of the "economic" dimension of political ideology: how do we cooperate with one another, and how do we share the spoils of that cooperation? In addition, the dual evolutionary framework predicts that variation in a willingness to cooperate with others should covary with the economic dimension of ideology.

Across all four empirical chapters in this thesis, I found evidence for a relationship between cooperative behaviour and measures of the economic dimension of political ideology. In New Zealand, cooperative behaviour was negatively associated with SDO and a host of economically conservative policy views (Chapter 3) and was a major predictor of support for economically progressive political parties (Chapter 4). Longitudinal analyses revealed that cooperative behaviour predicted future changes in SDO and income redistribution views, suggesting a causal role (Chapter 5). In the United States, cooperative behaviour in mini-Dictator Games was also negatively related to SDO across all distribution decisions (Chapter 6). While the relationship between cooperation and SDO is well supported in the literature [@Thielmann2020], I have shown that this relationship extends to economic policy views, political party support, and longitudinal change over time, and these effects persist after controlling for RWA and socio-demographic variables known to predict political attitudes.

Chapter 3 revealed that cooperative behaviour in a battery of economic games could be explained by an underlying latent variable: the "cooperative phenotype". This replicated previous studies identifying the cooperative phenotype in the United States [@Peysakhovich2014] and Europe [@Reigstad2017], and generalised these findings to New Zealand. Subsequent analyses showed that this cooperative phenotype was stable within individuals over eighteen months and was associated with a variety of "economic" political attitudes. These findings contradict previous frameworks predicting that, for example, SDO should be related specifically to defection in exploitative situations [@Thielmann2020]. Instead, these findings are in line with the dual evolutionary framework, which predicts that political ideology should be related to a _general_ behavioural preference for cooperation that motivates behaviour across many different situations, including non-exploitative situations (e.g., coordination problems).

In all four empirical chapters, impersonal cooperative behaviour was directed towards anonymous strangers in one-shot games with no possibility for reciprocation. This supports the prediction from the dual evolutionary framework that economic progressives should not only be more willing to cooperate across a range of situations, but they should also be more willing to expand the sphere of impersonal cooperation to include fleeting interactions with unrelated strangers. However, it remains unclear if economic progressives and conservatives also differ in cooperation directed towards individuals with closer network ties, like family members. For example, one study of participants from the United States found that self-reported liberalism was associated with increased love for friends and love for all others, but conservatism was associated with increased love for family [@Waytz2019]. It also remains unclear whether economic progressives would continue to cooperate in repeated economic games following defection from other players. Since the dual evolutionary framework argues that the first key step in the evolution of human group living built upon mechanisms of kin selection and reciprocity that already existed, it predicts that there should be no difference in kin-directed or reciprocal cooperation between economic progressives and conservatives. As described below, future research could test this prediction using games with multiple rounds and identifiable recipients of cooperation.

The dual evolutionary framework also predicts that cooperation in economic progressives should be psychologically motivated by other-regarding preferences and empathic concern. However, the exploratory analyses Chapter 6 suggested that different motives underlie cooperation. These analyses revealed that cooperation in participants with low SDO scores was not motivated by selflessness (vs. self-interest), but was rather motivated by equality of payoffs. This suggests that the motivation underlying the economic dimension of ideology is more likely to be a "drive to equalise payoffs" than a "drive to maximise self-interest". Cooperation is one effective way to equalise payoffs [@Aktipis2016], but there are others ways, including punishment of high earners [@Raihani2019].

Two related yet distinct psychological mechanisms might underlie this behavioural preference for equality among economic progressives [@Starmans2017]. The first psychological mechanism is "inequality aversion", a preference for equal outcomes. Under this view, economic progressives behave (and vote) in such a way as to achieve an equal distribution of resources, regardless of the merit, need, or deservingness of recipients, while economic conservatives are not as averse to inequality. The second psychological mechanism is a universal concern with economic _unfairness_. Under this alternative view, economic progressives and conservatives both uphold principles of fairness (i.e., allocating resources proportional to the merit, need, and deservingness of recipients), but what differs between them is the extent to which they view recipients as needy or deserving.

If the behavioural preference for equality among economic progressives is motivated by variation in the psychological mechanism of inequality aversion, this has implications for the dual evolutionary theory of political ideology. The core argument for the economic dimension of ideology remains unchanged: the first key step in the evolution of human group living was associated with increases in both obligate cooperative foraging _and_ egalitarianism within groups [@Sterelny2016]. What needs explaining is how evolution could have sustained strategic variation in inequality aversion. Building on mechanisms introduced in Chapter 2, such variation can be explained by fitness trade-offs and behavioural plasticity. Evolutionary game theory suggests that inequality-averse and inequality-unaverse strategies can coexist in a population if benefits and costs arise for both strategies when playing different classes of game [@Muller2014]. Humans also calibrate their inequality aversion depending on a variety of situational cues, such as random resource allocation [@Starmans2017]. Thus, evolution could favour strategic variation in inequality aversion through heritable individual differences combined with the presence of relevant situational cues.

Alternatively, the behavioural preference for equality among economic progressives might be motivated by differing perceptions of effort and merit feeding into a universal concern for economic fairness. A universal psychological concern for fairness in humans is predicted by evolutionary theories of cooperation via partner choice [@Baumard2013]. Under this view, a concern for fairness emerges from competition between cooperators: those who give too little are ostracised, but those who give too much are exploited. This results in psychological mechanisms that, when distributing resources, favour impartiality and proportionality according to perceptions of effort and merit. Indeed, there is some evidence that a universal concern for fairness, interacting with differing perceptions of effort and merit, predicts political attitudes. For example, research has revealed that manipulating perceptions of need and merit for welfare recipients influences opinions on welfare: people support welfare payments if they believe the recipients deserve them [@Petersen2011]. But it remains unclear whether such perceptions motivated individual differences in the behavioural preference for equality in Chapter 6, since this study did not include explicit manipulations of effort or merit. As discussed below, to tease apart the two alternative accounts of economic ideology, future research should distinguish between (1) behavioural preferences for cooperation vs. equal outcomes, and (2) psychological preferences for economic equality vs. economic fairness.

### The "social" dimension of political ideology

As well as increases in obligate cooperation, the transition from small great ape bands to more complex hunter-gatherer communities was also associated with increases in group-mindedness, in which humans began to conform to group-wide cultural norms and enforce those norms on other group members [@Tomasello2012; @Tomasello2016; @Sterelny2016]. This shift towards group conformity resulted in hunter-gatherer groups governed by cultural practices, traditions, and institutions, in stark contrast to earlier proto-cultural social life associated with great apes [@Henrich2015]. Chapter 2 argues that this shift from individualism to group conformity explains the domain of the "social" dimension of political ideology: which cultural norms do we adhere to, how do we delineate the boundaries of the cultural group, and how do we sanction norm violators? In addition, the dual evolutionary framework predicts that variation in a general behavioural preference for group conformity should covary with measures of this ideological dimension.

Across the four empirical chapters in this thesis, evidence for a relationship between conformist behavioural preferences and the social dimension of political ideology found mixed support, depending on the behavioural task being used. Supporting the dual evolutionary framework, conformity in the form of social information use [measured by the BEAST; @Molleman2019] was related to RWA and social policy views, and weakly related to support for the socially conservative New Zealand First Party (Chapters 3 and 4). These associations persisted controlling for SDO and socio-demographic variables. In the United States, authoritarians also rated distributions of experimental points as more socially inappropriate (i.e., they perceived harsher social norms; Chapter 6). These behavioural findings expand upon previous research highlighting, among conservatives, increased ratings of social inappropriateness in response to social norm violations [@Desilets2020] and increased conformity to social information in the form of perceived within-group consensus and desire for shared reality [@Jost2018]. 

However, several results were inconsistent with the dual evolutionary framework. In New Zealand, conformity in the form of norm-enforcing punishment and rule following was unrelated to RWA, and instead was related to SDO (Chapter 3). In the United States, RWA was also unrelated to the normative utility component measuring adherence to social norms (Chapter 6).

Taking both the consistent and inconsistent results at face value, one might conclude that the social dimension of political ideology covaries with informational conformity and perceptions of the severity of social norms, but _not_ with adherence to or enforcement of those norms. Such a conclusion would be difficult to reconcile with the dual evolutionary foundations framework, which highlights norm enforcement and norm adherence as two important elements of group conformity. This conclusion would also stand in stark contradiction to the wider psychological literature on authoritarianism, which has found that authoritarians report greater endorsement of strong punitive measures [@Capps2002], including capital and corporal punishment [@Feather2002; @Benjamin2006], and strict adherence to conventions and tradition [@Altemeyer1981].

A possible explanation for this pattern of behavioural results, discussed in Chapter 3, is that the tasks used to measure norm adherence and norm enforcement --- the punishment games, the rule following task, and the mini-Dictator Games --- are not good measures of group conformity _per se_. These behavioural tasks are anonymous, completed individually without reference to group membership, and conducted in a cultural vacuum (i.e., without reference to real cultural norms). These issues bring into question the construct validity of the punishment, rule following, and mini-Dictator Game tasks as measures of group conformity. Instead, it is likely that these tasks are tapping into vengeful and competitive motives. Previous research has shown that "norm-enforcing" punishment in economic games is associated with the self-reported frequency of vengeful thoughts [i.e., "[thinking] about how to get revenge on someone you had been angry at"; @Peysakhovich2014]. Punishment can also serve competitive functions that may be unrelated to norm enforcement or deterrence, such as elevating one's payoff relative to others [@Raihani2019]. These vengeful and competitive motives can explain the positive relationship between SDO and punishment in Chapter 3.  Moreover, both the rule following task and the normative utility component in the mini-Dictator Games appear to capture a willingness to cheat for personal gain. In the rule following task, cheating takes the form of breaking the rule for more money, while for normative utility component, cheating takes the form of behaving in a socially inappropriate way for more money. Indeed, Chapter 6 revealed that rule following and the normative utility component were positively correlated, and Chapter 3 showed that rule following was related to SDO, not RWA. In the next section, I propose alternative behavioural measures of group conformity that overcome some of these issues.

Another curious pattern of results emerged from authoritarian reactions to overly generous behaviour. In the first study in Chapter 3, right-wing authoritarianism was related to anti-social punishment (i.e., reducing the payoff of cooperators at a personal cost). Similarly, in Chapter 6, right-wing authoritarians gave higher social inappropriateness ratings for ultra-cooperative decisions. While these findings initially appear to link authoritarianism to cooperation rather than group conformity, upon reflection they are in line with the dual evolutionary framework. In Chapter 6, I proposed that these negative reactions to overly generous behaviour could be a form of "do-gooder derogation" [@Minson2012; @Pleasant2018] in which authoritarians are protecting themselves from normative judgement by generous individuals. Previous work also suggests that anti-social punishment can reflect normative conformity, insofar as punishers perceive both overly selfish _and_ overly cooperative individuals as violators of equality norms [@Herrmann2008]. This aligns with the prediction from the dual evolutionary framework that social conservatives can adhere to and enforce norms of defection as well as cooperation.

Finally, it is worth noting that this thesis has focused specifically on measuring group conformist preferences among _right-wing_ authoritarians. However, left-wing people can also express authoritarian sensibilities. In recent years, left-wing authoritarianism has emerged as a psychological construct measuring left-wing attitudes such as anti-hierarchical aggression and support for top-down censorship [@Conway2018; @Costello2020]. Left-wing authoritarians report support for the suppression of right-wing views (e.g., censoring racist or sexist material) and harsh enforcement of egalitarian norms (e.g., stripping rich people of their wealth). Like their right-wing counterparts, left-wing authoritarians also espouse conformist values [e.g., obedience, honouring elders; @Costello2020]. From the perspective of the dual evolutionary framework, left-wing authoritarians are individuals with a combination of cooperative and group conformist preferences. In order to fully understand the social dimension of political ideology, group conformist preferences must be related to both right-wing _and_ left-wing authoritarianism.

## Future directions

The empirical work presented in this thesis has begun to validate the dual evolutionary theory of political ideology. But much work is still needed to clarify the links between behavioural preferences and political attitudes and test additional predictions of the theory. In this section, I outline several promising avenues for future research.

### Further testing the relationships between behavioural preferences and political attitudes

In cross-sectional correlational studies that link behavioural preferences and political ideology, the direction of causality is never certain. People with particular behavioural preferences might adopt particular political attitudes and values as a result. Or people's attitudes and values might affect how they interpret and behave in experimental tasks. While cross-sectional approaches cannot disentangle these casual models, longitudinal approaches are one powerful method of inferring causality in non-experimental data [@Hamaker2015]. Chapter 5 introduced this approach to the study of behavioural preferences and political ideology. Future research could expand this approach by (1) collecting further waves of behavioural and self-report data, and (2) relating behavioural data from childhood to later political attitudes.

First, future research should collect further waves of data. Due to time constraints, I was only able to collect two waves of behavioural data in this thesis. Additional waves of data would empower researchers to ask more nuanced questions about the longitudinal relationships between behaviour and ideology. In particular, with three or more waves of data, researchers could model longitudinal effects using random-intercept cross-lagged panel models that correctly separate within-person change from stable between-person differences [@Hamaker2015], improving upon the methods used in Chapter 5. With further waves of data, changes in RWA could also be related to changes in social information use and other measures of group conformity.

Second, research should test the predictions that variation in cooperative and conformist behaviour at a young age will predict the two dimensions of political ideology decades later. Building on prior work showing that personality in young children predicts later placement along a liberal-conservative dimension [@Block2006], the dual evolutionary foundations framework makes the more specific predictions that sharing and helping behaviour in childhood will negatively predict economic (but not social) conservatism in adulthood, while feelings of guilt, focus on social norms, and enforcement of rules in childhood will positively predict social (but not economic) conservatism in adulthood. Longitudinal developmental designs will be required to test these predictions.

Future studies of behavioural preferences and political attitudes, whether cross-sectional or longitudinal, should also further refine the behavioural tasks used to measure cooperative and conformist dispositions. To study whether economic progressives will continue to cooperate over multiple interactions, researchers could employ repeated rather than one-shot economic games. To further map out the breadth of the cooperative sphere (i.e., do people extend their cooperation to family, friends, acquaintances, or beyond?), researchers could move away from anonymous games and towards games with identifiable partners [e.g., @Gervais2017]. To distinguish between preferences for equal outcomes and cooperation, researchers could use social value orientation tasks that pit two types of resource distribution against one another: equal distributions that produce suboptimal group-level payoffs and unequal distributions that maximise group-level payoffs [@Murphy2011; @Mischkowski2019]. While previous work with social value orientation tasks has identified individualist, competitor, and prosocial types and found that self-reported liberals tend to fit into the latter type [@VanLange2012], this work did not relate the two dimensions of political ideology to inequality aversion and joint gain maximisation. Given our findings in Chapter 6, we might predict that economic progressives would prefer the equal resource distribution, even at the expense of group-level benefits. Researchers could also employ "heterogeneous" public goods games in which group members receive varying returns from the shared public account [@Gangadharan2017]. In these adapted public goods games, cooperating with the group results in greater inequality of payoffs between group members. If economic progressives are driven by a behavioural preference for equality, they should cease to cooperate in such situations. Finally, research could tease apart economic inequality and economic unfairness by systematically varying the extent to which participants "earn" their endowments in economic games and determining whether such manipulations affect behavioural preferences for equality among economic progressives. Together, these refinements will provide a deeper understanding of the extent of cooperation among economic progressives and the proximate motivations underlying this behaviour.

To avoid ambiguity in the interpretation of previous measures of group conformist preferences, future research could use behavioural tasks that fit the following criteria. First, the tasks could include some references to group membership, either real or experimentally-imposed using minimal-group paradigms. For example, instructions could reveal that participants are from different countries, or belong to different randomly-allocated teams. Second, the tasks could highlight existing cultural cleavages and measure enforcement of and adherence to _real_ cultural norms that differ across those divides. For example, @Halali2018 tested hypotheses about the behavioural correlates of SDO by sampling from real cultural groups with histories of inter-group conflict, finding in one study that SDO was related to behavioural selfishness in both Jewish and Palestinian participants in Israel. A similar approach could be used to study the behavioural correlates of authoritarianism and social conservatism, but instead measuring norm enforcement and norm adherence within groups. Third, the tasks could employ centralised punishment institutions rather than peer-to-peer punishment systems [e.g., @Gurerk108], since authoritarians are thought to be particularly supportive of strong authoritative institutions [@Altemeyer1981]. Fourth, field experiments of social norm adherence and rule breaking in real-world scenarios [e.g., dodging public transportation fares; @Dai2018] might also be useful to relate to the social dimension of ideology, since normative behaviour is public rather than anonymous and the existing social norms are clear. In order to develop a complete picture of the social dimension of political ideology, behavioural tasks that fit these criteria should be associated with both right-wing _and_ left-wing authoritarianism.

### Testing additional predictions of the dual evolutionary foundations of political ideology

The hypothesis that behavioural preferences for cooperation and group conformity should covary with the two dimensions of political ideology is only one prediction that emerges from the dual evolutionary foundations framework. The framework also makes predictions about the kinds of threats that should impact each of the ideological dimensions, and the ubiquity of the two dimensions and their structure across cultures. These predictions should additionally be tested to provide a richer empirical foundation for the dual evolutionary framework.

Our theory predicts that competitive and threatening socio-environmental conditions should differentially predict the two dimensions of ideology. Previous work has shown that high-profile events like terrorism can increase conservatism [@Nail2009], but this work has largely considered only a single dimension of ideology. The dual evolutionary framework makes more nuanced predictions. For example, acute events invoking threat (e.g., disease outbreaks), particularly group threats (e.g., terrorism and warfare), should induce short-term increases in social (but not economic) conservatism. Chronic conditions, either actual or perceived, invoking competitive hierarchy [e.g., income resulting from effort rather than luck; @Alesina2011] or threats to group viability (e.g., political unrest and criminality) should predict economic and social conservatism, respectively. These various predictions could be tested using vignette designs, where participants read about different situations and are subsequently asked about their political views. Another approach might be real-world natural experiments, where people's attitudes and values are measured before and after large-scale events like pandemics and natural disasters [@Fischer2020; @Vardy2019].

The dual evolutionary framework also predicts that we should be able to identify the two dimensions of cooperation and group conformity even in non-WEIRD (Western, educated, industrialised, rich, and democratic) societies [@Henrich2010] and small-scale societies. While this thesis was limited to WEIRD samples, social conservatives in non-WEIRD and small-scale societies should similarly be sensitive to local threats to group viability and should adhere to and enforce local norms and taboos, the content of which will differ from culture to culture. Testing these predictions will require newly devised self-report scales targeting cooperative and conformist preferences without culture-specific political content [e.g., avoiding US-centric items like those measuring RWA; @Altemeyer1981]. Such scales hold the promise of a sturdier theoretical foundation for political science and more robust measures of the two dimensions of political ideology across cultures.

Finally, while our theory suggests that the two dimensions of political ideology should be largely independent, it also predicts that correlations between the two dimensions within populations are more likely to be negative than positive, since cooperative norms are more beneficial for the group. Indeed, economic and social conservatism are weakly to moderately negatively correlated across much of the world [@Malka2019]. But more research is needed into why, compared to other cultures, Western countries such as Great Britain and the United States are outliers in showing a _positive_ correlation between scores on the two dimensions [@Malka2019]. Do modern capitalist social norms and party politics in these countries encourage social conservatives to adopt more competitive views? Or can the cultural origins of these differences be traced back much further to the effects of religion [@Schulz2019], agriculture [@Talhelm2014], or deep linguistic ancestry [@Matthews2016]? Modern cross-cultural comparative methods, such as cultural phylogenetics [@Sheehan2018] and global time-series analyses [@Ruck2020], have the potential to answer such questions about the cultural evolution of human political institutions.

### Towards a transparent and reproducible science of psychology

As the previous sections have outlined, there is much for psychologists to be working on. But the question remains: _how_ should they go about conducting this work? Are the current research practices in psychology up to the job? Or is there scope for improvement? While I still have the floor, I would like to briefly argue that psychology has some way to go before it can claim the status of a rigorous cumulative science. To achieve this goal, our field must improve two features of research practice in particular, features that I have tried to exemplify in this thesis: transparency and reproducibility.

Psychology is currently undergoing a "replication crisis" [@Shrout2018]. Over the last decade, many foundational results in the field have failed to replicate [@OpenScienceCollaboration2015], leading to suggestions that the discipline is built on a combination of false positive findings, publication bias, and questionable research practices [@Chambers2019]. This has prompted several recommendations for scientific reform in psychology [@Nosek2015; @Munafo2017], including the adoption of research practices that are transparent (e.g., preregistration of hypotheses, open data, open materials) and reproducible (e.g., open analysis code for other researchers to independently validate statistical results). Yet, despite these recommendations, a random sample of the literature from 2014 to 2017 revealed continued low levels of transparency in published psychological research [@Hardwicke2021a], and less than half of studies with "open data badges" published in the journal _Psychological Science_ between 2014 and 2015 contained statistical results that were reproducible from the original data without input from the study authors [@Hardwicke2021b].

This thesis represents my attempt to meet the recommendations of the "credibility revolution" in psychology [@Vazire2018]. In terms of transparency, the materials from all chapters of this thesis (e.g., Python code for economic games, Qualtrics surveys) have been made publicly available. Three of the four empirical chapters in this thesis were preregistered, with hypotheses and analysis plans publicly timestamped on the Open Science Framework ([https://osf.io/](https://osf.io/)) prior to data collection. Where analyses were not preregistered, I have made clear that any findings should be considered exploratory. One chapter in this thesis has publicly available raw data, while the data for the other three chapters are available upon request to qualified researchers. This is because these data were collected alongside the longitudinal New Zealand Attitudes and Values Study, which has constraints on open data sharing due to ethical concerns such as informed consent and privacy. But on the whole, I have strived to make my research open and transparent where possible. Such transparency improves the accessibility of research, both to the general public and interested researchers, and increases the likelihood of others being able to successfully replicate the studies with new data, a necessary condition for any cumulative science [@Nosek2015].

As well as being able to replicate studies with new data, researchers should be able to reproduce a study's statistical results with the _original_ data [@Patil2016]. As statistical models and computational research pipelines increase in complexity, reproducibility becomes vital for cumulative science. Using a combination of R Markdown [@R-markdown] and the reproducible workflow R package _drake_ [@R-drake], I have endeavoured to make this thesis as reproducible as possible, from data to finished manuscript. The R code for this entire thesis, including analysis code and raw Markdown chapters, can be found here: https://github.com/ScottClaessens/thesis. Since some of the data from the New Zealand Attitudes and Values Study is not publicly available, the chapters are not immediately 100% reproducible. But if the raw data files are requested and placed in the correct folders, one should be able to reproduce this entire thesis, including all statistical models and numerical results, at the click of a button. Such a reproducible workflow makes clear how statistical parameters were arrived at, thus improving trust in the results.

Psychology is transitioning through a methodological revolution, and transparency and reproducibility are front and centre of that revolution. I hope that the work in this thesis sets a positive example for future psychological research testing predictions of the dual evolutionary framework of political ideology.

## Conclusion

The dual evolutionary foundations of political ideology provide a new lens through which to view human political behaviour. The framework is rooted in the social tensions that have always structured and will continue to structure human social groups: the tension between competition and cooperation, and the tension between individualism and group conformity. The theory makes sense of decades of work in political psychology pointing to two dimensions of political ideology, and synthesises recent evolutionary approaches to politics. It also makes novel predictions about the structure and correlates of political attitudes, some of which have been borne out by the empirical work in this thesis. I hope that the framework presented here continues to provide fruitful ground for research on the evolutionary origins of the human political animal.
